# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Flashcards\Flashcards\ui\main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main_Menu(object):
    def setupUi(self, Main_Menu):
        Main_Menu.setObjectName("Main_Menu")
        Main_Menu.resize(1920, 1080)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/Picture/cards.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Main_Menu.setWindowIcon(icon)
        Main_Menu.setStyleSheet("background-image: url(:/image/Picture/main_menu.jpg);")
        self.centralwidget = QtWidgets.QWidget(Main_Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_AE = QtWidgets.QPushButton(self.centralwidget)
        self.btn_AE.setGeometry(QtCore.QRect(760, 320, 296, 181))
        self.btn_AE.setStyleSheet("QPushButton{\n"
"    background:transparent;\n"
"    background-image: url(:/image/Picture/btn_ae.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #8DC68F;\n"
"}")
        self.btn_AE.setText("")
        self.btn_AE.setObjectName("btn_AE")
        self.btn_FJ = QtWidgets.QPushButton(self.centralwidget)
        self.btn_FJ.setGeometry(QtCore.QRect(1100, 320, 296, 181))
        self.btn_FJ.setStyleSheet("QPushButton{\n"
"    background:transparent;\n"
"    background-image: url(:/image/Picture/btn_fj.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #8DC68F;\n"
"}")
        self.btn_FJ.setText("")
        self.btn_FJ.setObjectName("btn_FJ")
        self.btn_KO = QtWidgets.QPushButton(self.centralwidget)
        self.btn_KO.setGeometry(QtCore.QRect(1440, 320, 296, 181))
        self.btn_KO.setStyleSheet("QPushButton{\n"
"    background:transparent;\n"
"    background-image: url(:/image/Picture/btn_ko.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #8DC68F;\n"
"}")
        self.btn_KO.setText("")
        self.btn_KO.setObjectName("btn_KO")
        self.btn_PT = QtWidgets.QPushButton(self.centralwidget)
        self.btn_PT.setGeometry(QtCore.QRect(940, 620, 296, 181))
        self.btn_PT.setStyleSheet("QPushButton{\n"
"    background:transparent;\n"
"    background-image: url(:/image/Picture/btn_pt.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #8DC68F;\n"
"}")
        self.btn_PT.setText("")
        self.btn_PT.setObjectName("btn_PT")
        self.btn_UZ = QtWidgets.QPushButton(self.centralwidget)
        self.btn_UZ.setGeometry(QtCore.QRect(1300, 620, 296, 181))
        self.btn_UZ.setStyleSheet("QPushButton{\n"
"    background:transparent;\n"
"    background-image: url(:/image/Picture/btn_uz.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #8DC68F;\n"
"}")
        self.btn_UZ.setText("")
        self.btn_UZ.setObjectName("btn_UZ")
        Main_Menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Main_Menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        Main_Menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Main_Menu)
        self.statusbar.setObjectName("statusbar")
        Main_Menu.setStatusBar(self.statusbar)

        self.retranslateUi(Main_Menu)
        QtCore.QMetaObject.connectSlotsByName(Main_Menu)

    def retranslateUi(self, Main_Menu):
        _translate = QtCore.QCoreApplication.translate
        Main_Menu.setWindowTitle(_translate("Main_Menu", "MainMenu"))
import vocab_pic1_rc
