# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Flashcards\Flashcards\ui\play_ae.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Play_AE(object):
    def setupUi(self, Play_AE):
        Play_AE.setObjectName("Play_AE")
        Play_AE.resize(1920, 1080)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/Picture/cards.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Play_AE.setWindowIcon(icon)
        Play_AE.setStyleSheet("background-image: url(:/image/Picture/play_menu.jpg);")
        self.centralwidget = QtWidgets.QWidget(Play_AE)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_play = QtWidgets.QPushButton(self.centralwidget)
        self.btn_play.setGeometry(QtCore.QRect(690, 400, 88, 88))
        self.btn_play.setStyleSheet("background-image: url(:/image/Picture/play.png);")
        self.btn_play.setText("")
        self.btn_play.setIconSize(QtCore.QSize(20, 20))
        self.btn_play.setAutoDefault(False)
        self.btn_play.setDefault(False)
        self.btn_play.setFlat(True)
        self.btn_play.setObjectName("btn_play")
        self.btn_correct = QtWidgets.QPushButton(self.centralwidget)
        self.btn_correct.setGeometry(QtCore.QRect(232, 790, 421, 91))
        self.btn_correct.setStyleSheet("QPushButton{\n"
"    font: 25pt \"Mitr SemiBold\";\n"
"    color: rgb(255, 255, 255);\n"
"    background: #009933;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #009960;\n"
"}")
        self.btn_correct.setObjectName("btn_correct")
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(110, 90, 93, 93))
        self.btn_back.setStyleSheet("background-image: url(:/image/Picture/back.png);")
        self.btn_back.setText("")
        self.btn_back.setFlat(True)
        self.btn_back.setObjectName("btn_back")
        self.btn_show = QtWidgets.QPushButton(self.centralwidget)
        self.btn_show.setGeometry(QtCore.QRect(575, 500, 321, 71))
        self.btn_show.setStyleSheet("QPushButton{\n"
"    font: 25pt \"Mitr SemiBold\";\n"
"    color: dark;\n"
"    background: transparent;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #a3ffdd;\n"
"}")
        self.btn_show.setObjectName("btn_show")
        self.btn_incorrect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_incorrect.setGeometry(QtCore.QRect(809, 790, 421, 91))
        self.btn_incorrect.setStyleSheet("QPushButton{\n"
"    font: 25pt \"Mitr SemiBold\";\n"
"    color: rgb(255, 255, 255);\n"
"    background: #CC0033;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #CC0050;\n"
"}")
        self.btn_incorrect.setObjectName("btn_incorrect")
        self.label_question = QtWidgets.QLabel(self.centralwidget)
        self.label_question.setGeometry(QtCore.QRect(470, 310, 531, 51))
        self.label_question.setStyleSheet("font: 20pt \"Mitr SemiBold\";\n"
"background: transparent;")
        self.label_question.setAlignment(QtCore.Qt.AlignCenter)
        self.label_question.setObjectName("label_question")
        self.label_answer = QtWidgets.QLabel(self.centralwidget)
        self.label_answer.setGeometry(QtCore.QRect(470, 620, 531, 51))
        self.label_answer.setStyleSheet("font: 20pt \"Mitr SemiBold\";\n"
"background: transparent;")
        self.label_answer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_answer.setObjectName("label_answer")
        Play_AE.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Play_AE)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        Play_AE.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Play_AE)
        self.statusbar.setObjectName("statusbar")
        Play_AE.setStatusBar(self.statusbar)

        self.retranslateUi(Play_AE)
        QtCore.QMetaObject.connectSlotsByName(Play_AE)

    def retranslateUi(self, Play_AE):
        _translate = QtCore.QCoreApplication.translate
        Play_AE.setWindowTitle(_translate("Play_AE", "Play A-E"))
        self.btn_play.setToolTip(_translate("Play_AE", "<html><head/><body><p>กดปุ่มเพื่อเล่นสุ่มคำศัพท์</p></body></html>"))
        self.btn_correct.setText(_translate("Play_AE", "CORRECT"))
        self.btn_back.setToolTip(_translate("Play_AE", "<html><head/><body><p>กดปุ่มเพื่อกลับหน้าแรก</p></body></html>"))
        self.btn_show.setText(_translate("Play_AE", "SHOW ANSWER"))
        self.btn_incorrect.setText(_translate("Play_AE", "INCORRECT"))
        self.label_question.setText(_translate("Play_AE", "Question"))
        self.label_answer.setText(_translate("Play_AE", "Answer"))
import vocab_pic1_rc
